title : Cabinet de Game Design Clandestin
tagline: Quand le jeu de plateau rencontre le story telling... ça donne quoi ? Un blog avec du jeu de plateau dedans !
author :
  name : PYM et MRO
  email : gamedesigncabinet@gmail.com
  github : gamedesigncabinet
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
